[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
privacy_pool = "AfTSjfnT7M88XipRjPGLgDCcqcVfnrePrtuvNBF74hhP"

[programs.mainnet]
privacy_pool = "AfTSjfnT7M88XipRjPGLgDCcqcVfnrePrtuvNBF74hhP"

[programs.localnet]
privacy_pool = "AfTSjfnT7M88XipRjPGLgDCcqcVfnrePrtuvNBF74hhP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/privacy_pool"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
