leaf_index = ""
merkle_path = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
merkle_root = ""
new_commitment = ""
new_secret = ""
nullifier = ""
old_amount = ""
old_secret = ""
order_amount = ""
order_commitment = ""
order_salt = ""
